-- SUPERSEDED — do not run this file.
--
-- Studio already owns the membership schema, admin queue, and Resend emails:
--   rhood-studio/supabase/migrations/20260910180000_dj_membership_approval.sql
--
-- The DJ app reuses that schema (invite_code_used + redeem_dj_invite_code) plus
-- the existing waitlist screen, processReferral credits, and send-expo-push.
--
-- If you already ran an older copy of this file (finalize_dj_membership /
-- dj_membership_applications / guard with rhood.allow_membership_update = 'on'),
-- run database-migrations/align-dj-membership-with-studio.sql once so Studio's
-- CHECK constraints and admin_set_dj_membership can work.
