import { StyleSheet } from "react-native";

/**
 * Listen tab + related modals. Large by design; consider splitting by feature
 * (base / recommendations / playlists / modals) and sharing tokens via lib/sharedStyles.
 * Do not duplicate keys in this object — later entries silently override earlier ones.
 */
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "hsl(0, 0%, 0%)",
  },
  /** Single root for ListHeaderComponent layout */
  listenScreenHeaderRoot: {
    width: "100%",
  },
  /** Top of Listen tab: hero + always-visible upload entry */
  listenHomeTop: {
    width: "100%",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "hsl(0, 0%, 15%)",
  },
  /** Circular + control — create / upload mix */
  listenHeaderCreateButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "hsl(0, 0%, 10%)",
    borderWidth: 1,
    borderColor: "hsl(75, 100%, 50%)",
    alignItems: "center",
    justifyContent: "center",
  },
  /** Smaller section titles (Trending, Your playlists) on Listen */
  listenSectionHeroTitleCompact: {
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  /** Search row under Listen hero — uses full width of padded parent */
  listenHomeSearchSection: {
    marginTop: 4,
    marginBottom: 4,
    width: "100%",
  },
  listenHomeSearchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "hsl(0, 0%, 8%)",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "hsl(0, 0%, 15%)",
  },
  listenHomeSearchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    color: "hsl(0, 0%, 100%)",
    fontFamily: "Helvetica Neue",
  },
  listenScreenFooterRoot: {
    width: "100%",
  },
  header: {
    padding: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "hsl(0, 0%, 15%)",
  },
  tsBlockBoldHeading: {
    fontFamily: "TS Block Bold",
    fontSize: 18, // Reduced from 22 for better balance
    color: "#FFFFFF", // Brand white
    textAlign: "left", // Left aligned as per guidelines
    textTransform: "uppercase", // Always uppercase
    lineHeight: 22, // Adjusted line height
    letterSpacing: 0.5, // Reduced letter spacing
    marginBottom: 12, // Reduced margin for tighter spacing
  },
  headerSubtitle: {
    fontSize: 16,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 70%)",
  },
  flatListContent: {
    flexGrow: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 160,
  },
  section: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    marginBottom: 8,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    width: "100%",
  },
  /** @deprecated Prefer plain sectionTitle without icon row (matches Discover carousel headers). */
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  /** In-list section titles — same as Connections Discover recommendationsTitle (no icons, title case). */
  sectionTitle: {
    flex: 1,
    fontSize: 18,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 100%)",
    letterSpacing: 0.5,
    marginRight: 8,
  },
  /** Text action on section row (e.g. See all) — matches Connections sectionHeaderLink. */
  sectionHeaderLink: {
    fontSize: 13,
    fontFamily: "Helvetica Neue",
    fontWeight: "600",
    color: "hsl(75, 100%, 60%)",
    paddingVertical: 4,
    paddingLeft: 12,
  },
  sectionSubtitle: {
    fontSize: 13,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 60%)",
    marginBottom: 16,
    lineHeight: 18,
  },
  loadingContainer: {
    paddingVertical: 32,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 60%)",
    marginTop: 12,
  },
  emptyContainer: {
    paddingVertical: 40,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyIcon: {
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 16,
    fontFamily: "TS Block Bold",
    fontWeight: "600",
    color: "hsl(0, 0%, 80%)",
    marginBottom: 8,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 55%)",
    textAlign: "center",
    lineHeight: 20,
  },
  errorContainer: {
    paddingVertical: 24,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  errorText: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 80%, 55%)",
    marginBottom: 12,
    textAlign: "center",
  },
  retryButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: "hsl(75, 100%, 60%)",
  },
  retryButtonText: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    fontWeight: "600",
    color: "hsl(0, 0%, 0%)",
  },
  popularMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 2,
  },
  uploadSection: {
    padding: 16,
    paddingTop: 8,
  },
  uploadCard: {
    backgroundColor: "hsl(0, 0%, 5%)",
    borderRadius: 12,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "hsl(0, 0%, 15%)",
    borderStyle: "dashed",
  },
  uploadTitle: {
    fontSize: 18,
    fontFamily: "TS Block Bold",
    fontWeight: "900",
    color: "hsl(0, 0%, 100%)",
    marginTop: 12,
    marginBottom: 8,
  },
  uploadDescription: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 70%)",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
  },
  uploadButton: {
    backgroundColor: "hsl(75, 100%, 60%)",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  uploadButtonText: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    fontWeight: "600",
    color: "hsl(0, 0%, 0%)",
  },
  bottomSpacing: {
    height: 160, // Increased to account for play bar height and fade overlay
  },
  // Modal Styles - R/HOOD Theme
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "hsl(0, 0%, 8%)",
    borderRadius: 20,
    padding: 32,
    width: "85%",
    maxWidth: 400,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "hsl(75, 100%, 60%)",
  },
  modalIcon: {
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "white",
    marginBottom: 12,
    textAlign: "center",
  },
  modalDescription: {
    fontSize: 16,
    color: "hsl(0, 0%, 70%)",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 22,
  },
  modalButtons: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  modalCancelButton: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "hsl(0, 0%, 15%)",
    borderWidth: 1,
    borderColor: "hsl(0, 0%, 25%)",
    alignItems: "center",
  },
  modalCancelText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
  },
  modalUploadButton: {
    flex: 1,
    borderRadius: 12,
    overflow: "hidden",
  },
  modalUploadGradient: {
    padding: 14,
    alignItems: "center",
  },
  modalUploadText: {
    color: "black",
    fontSize: 16,
    fontWeight: "bold",
  },
  // Search Bar Styles
  searchWrapper: {
    margin: 20,
    marginBottom: 16,
    position: "relative",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "hsl(0, 0%, 8%)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "hsl(0, 0%, 15%)",
  },
  suggestionsContainer: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    backgroundColor: "hsl(0, 0%, 8%)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "hsl(0, 0%, 15%)",
    borderTopWidth: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    marginTop: -1,
    zIndex: 1000,
    maxHeight: 200,
  },
  suggestionItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "hsl(0, 0%, 15%)",
  },
  suggestionText: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 85%)",
    marginLeft: 12,
  },
  searchInput: {
    flex: 1,
    marginLeft: 12,
    fontSize: 16,
    color: "hsl(0, 0%, 100%)",
    fontFamily: "Helvetica Neue",
  },
  clearButton: {
    padding: 6,
    borderRadius: 12,
    backgroundColor: "hsl(0, 0%, 15%)",
    marginLeft: 8,
  },
  // Shuffle Styles
  shuffleContainer: {
    flexDirection: "row",
    paddingHorizontal: 20,
    marginBottom: 12,
    gap: 8,
  },
  shuffleButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "hsl(0, 0%, 8%)",
    borderWidth: 1,
    borderColor: "hsl(75, 100%, 60%, 0.3)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 6,
  },
  shuffleButtonText: {
    fontSize: 12,
    fontFamily: "Helvetica Neue",
    fontWeight: "600",
    color: "hsl(75, 100%, 60%)",
  },
  // Genre Filter Styles
  genreFilterContainer: {
    marginBottom: 16,
    marginTop: 8,
  },
  genreFilterContent: {
    paddingHorizontal: 20,
    gap: 8,
    paddingRight: 20,
  },
  genreChip: {
    backgroundColor: "hsl(0, 0%, 12%)", // Slightly lighter background
    borderWidth: 1.5, // Thicker border for better visibility
    borderColor: "hsl(0, 0%, 25%)", // Lighter border color
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  genreChipActive: {
    backgroundColor: "hsl(75, 100%, 60%)",
    borderColor: "hsl(75, 100%, 60%)",
  },
  genreChipText: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    fontWeight: "500",
    color: "hsl(0, 0%, 85%)", // Lighter text for better contrast
  },
  genreChipTextActive: {
    color: "hsl(0, 0%, 0%)",
    fontWeight: "600",
  },
  // Empty State Styles
  emptyState: {
    alignItems: "center",
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptyStateTitle: {
    fontSize: 18,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 100%)",
    marginTop: 16,
    marginBottom: 8,
  },
  emptyStateSubtitle: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 60%)",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 24,
  },
  emptyStateButton: {
    backgroundColor: "hsl(75, 100%, 60%)",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  emptyStateButtonText: {
    fontSize: 16,
    fontFamily: "Helvetica Neue",
    fontWeight: "600",
    color: "hsl(0, 0%, 0%)",
    textAlign: "center",
  },
  // Recommendations (horizontal strip + cards — single source of truth; was duplicated earlier in file)
  recommendationsSection: {
    marginBottom: 24,
    paddingHorizontal: 20,
  },
  recommendationsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    width: "100%",
  },
  recommendationsTitle: {
    flex: 1,
    fontSize: 18,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 100%)",
    letterSpacing: 0.5,
    marginRight: 8,
  },
  recommendationsScroll: {
    marginHorizontal: -20,
  },
  recommendationsContent: {
    paddingHorizontal: 20,
    gap: 16,
  },
  recommendationCard: {
    width: 160,
    height: 200,
    backgroundColor: "hsl(0, 0%, 8%)",
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "hsl(75, 100%, 60%, 0.1)",
  },
  recommendationImageContainer: {
    position: "relative",
    width: "100%",
    height: "100%",
    flex: 1,
  },
  recommendationImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "hsl(0, 0%, 12%)",
  },
  recommendationPlayingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
  },
  recommendationGradientOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "50%",
  },
  recommendationInfo: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 12,
    gap: 4,
    zIndex: 1,
  },
  recommendationTitle: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    fontWeight: "600",
    color: "hsl(0, 0%, 100%)",
  },
  recommendationArtist: {
    fontSize: 12,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 85%)",
  },
  recommendationGenre: {
    fontSize: 11,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 60%)",
    marginTop: 2,
  },
  viewAllButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "rgba(75, 255, 150, 0.12)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "hsl(75, 100%, 60%, 0.4)",
  },
  viewAllText: {
    fontSize: 13,
    fontFamily: "Helvetica Neue",
    fontWeight: "600",
    color: "hsl(75, 100%, 60%)",
    marginRight: 4,
  },
  recommendationsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    marginTop: 16,
    paddingHorizontal: 20,
  },
  recommendationGridCard: {
    width: "48%",
    backgroundColor: "hsl(0, 0%, 8%)",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "hsl(75, 100%, 60%, 0.1)",
  },
  recommendationGridImage: {
    width: "100%",
    height: 140,
    borderRadius: 16,
    backgroundColor: "hsl(0, 0%, 12%)",
  },
  recommendationGridText: {
    padding: 16,
    gap: 6,
  },
  // Popular releases style list (for More Like This)
  popularList: {
    marginTop: 8,
  },
  sectionItemWrap: {
    marginTop: 8,
  },
  popularRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "hsl(0, 0%, 15%)",
  },
  popularImageWrap: {
    width: 72,
    height: 72,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "hsl(0, 0%, 12%)",
  },
  popularImage: {
    width: "100%",
    height: "100%",
  },
  popularInfo: {
    flex: 1,
    gap: 4,
  },
  popularTitle: {
    fontSize: 12,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 100%)",
  },
  popularSubtitle: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 80%)",
  },
  popularMeta: {
    fontSize: 13,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 60%)",
  },
  likeButton: {
    padding: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  recommendationLikeButton: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  partialCardIndicator: {
    width: 60,
    justifyContent: "center",
    alignItems: "center",
  },
  partialCard: {
    width: 50,
    height: 50,
    backgroundColor: "hsl(0, 0%, 8%)",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "hsl(75, 100%, 60%)",
  },
  partialCardText: {
    fontSize: 10,
    fontFamily: "Helvetica Neue",
    fontWeight: "600",
    color: "hsl(75, 100%, 60%)",
    marginTop: 2,
  },
  genreRowsSection: {
    marginTop: 36,
    gap: 32,
  },
  genreRow: {
    backgroundColor: "transparent",
    borderRadius: 18,
    paddingVertical: 28,
    paddingHorizontal: 20,
    borderWidth: 0,
    borderColor: "transparent",
    marginHorizontal: 20,
  },
  genreRowHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  genreRowTitle: {
    fontSize: 18,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 100%)",
    letterSpacing: 0.5,
  },
  genreRowToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: "rgba(75, 255, 150, 0.12)",
  },
  genreRowToggleText: {
    fontSize: 12,
    fontFamily: "Helvetica Neue",
    fontWeight: "600",
    color: "hsl(75, 100%, 60%)",
  },
  genreRowContent: {
    gap: 20,
  },
  genreRowCard: {
    width: 180,
    height: 220,
    backgroundColor: "transparent",
    borderRadius: 16,
    borderWidth: 0,
    borderColor: "transparent",
    overflow: "hidden",
    justifyContent: "flex-end",
  },
  genreRowImage: {
    ...StyleSheet.absoluteFillObject,
  },
  genreRowGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  genreRowTextOverlay: {
    padding: 16,
    gap: 4,
  },
  genreRowMixTitle: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    fontWeight: "600",
    color: "hsl(0, 0%, 100%)",
  },
  genreRowMixArtist: {
    fontSize: 12,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 60%)",
  },
  recommendationExplainer: {
    fontSize: 12,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 60%)",
    marginTop: 4,
    marginBottom: 16,
    paddingHorizontal: 20,
    lineHeight: 16,
  },
  genreRowExplainer: {
    fontSize: 12,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 60%)",
    marginTop: 4,
    lineHeight: 16,
  },
  // Playlist Styles
  playlistsList: {
    marginTop: 8,
  },
  playlistRowWrap: {
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  /** Horizontal “Your playlists” strip — same horizontal inset as trendingRowWrap */
  playlistStripWrap: {
    paddingHorizontal: 20,
    marginBottom: 8,
  },
  playlistStripContent: {
    paddingRight: 20,
    gap: 14,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  playlistSquareCard: {
    width: 136,
  },
  playlistSquareTouchable: {
    width: 136,
    minWidth: 136,
    flexShrink: 0,
    alignItems: "flex-start",
  },
  playlistSquareImageWrap: {
    width: 136,
    height: 136,
    borderRadius: 12,
    backgroundColor: "hsl(0, 0%, 10%)",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "hsl(0, 0%, 18%)",
    justifyContent: "center",
    alignItems: "center",
  },
  playlistSquareImage: {
    width: "100%",
    height: "100%",
  },
  playlistSquareTitle: {
    fontSize: 13,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 100%)",
    marginTop: 10,
    letterSpacing: 0.3,
    lineHeight: 16,
  },
  playlistSquareMeta: {
    fontSize: 12,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 55%)",
    marginTop: 4,
  },
  trendingRowWrap: {
    paddingHorizontal: 20,
  },
  playlistRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 14,
    gap: 12,
    borderRadius: 12,
    backgroundColor: "hsl(0, 0%, 10%)",
  },
  playlistIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: "hsl(0, 0%, 12%)",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  playlistImage: {
    width: 48,
    height: 48,
    borderRadius: 8,
  },
  playlistInfo: {
    flex: 1,
    gap: 4,
  },
  playlistName: {
    fontSize: 16,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 100%)",
  },
  playlistMeta: {
    fontSize: 13,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 60%)",
  },
  // Save to Playlist Modal Styles
  playlistModalContent: {
    backgroundColor: "hsl(0, 0%, 8%)",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "80%",
    width: "90%",
    maxWidth: 500,
    paddingBottom: 20,
  },
  playlistModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "hsl(0, 0%, 15%)",
  },
  playlistModalTitle: {
    fontSize: 20,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 100%)",
    fontWeight: "bold",
  },
  playlistModalClose: {
    padding: 4,
  },
  playlistMixPreview: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "hsl(0, 0%, 15%)",
  },
  playlistMixPreviewImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
  },
  playlistMixPreviewInfo: {
    flex: 1,
    gap: 4,
  },
  playlistMixPreviewTitle: {
    fontSize: 16,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 100%)",
  },
  playlistMixPreviewArtist: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 70%)",
  },
  playlistModalScroll: {
    maxHeight: 400,
  },
  createPlaylistSection: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "hsl(0, 0%, 15%)",
  },
  createPlaylistTitle: {
    fontSize: 16,
    fontFamily: "Helvetica Neue",
    fontWeight: "600",
    color: "hsl(0, 0%, 100%)",
    marginBottom: 12,
  },
  createPlaylistInputContainer: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  createPlaylistInput: {
    flex: 1,
    backgroundColor: "hsl(0, 0%, 12%)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 100%)",
    borderWidth: 1,
    borderColor: "hsl(0, 0%, 20%)",
    minHeight: 48,
  },
  createPlaylistButton: {
    backgroundColor: "hsl(75, 100%, 60%)",
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
    minWidth: 80,
    alignItems: "center",
    justifyContent: "center",
  },
  createPlaylistButtonDisabled: {
    opacity: 0.5,
  },
  createPlaylistButtonText: {
    fontSize: 16,
    fontFamily: "Helvetica Neue",
    fontWeight: "600",
    color: "hsl(0, 0%, 0%)",
  },
  existingPlaylistsSection: {
    padding: 20,
  },
  existingPlaylistsTitle: {
    fontSize: 16,
    fontFamily: "Helvetica Neue",
    fontWeight: "600",
    color: "hsl(0, 0%, 100%)",
    marginBottom: 12,
  },
  existingPlaylistItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "hsl(0, 0%, 15%)",
  },
  existingPlaylistIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "hsl(0, 0%, 12%)",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  existingPlaylistImage: {
    width: 40,
    height: 40,
    borderRadius: 8,
  },
  existingPlaylistInfo: {
    flex: 1,
    gap: 4,
  },
  existingPlaylistName: {
    fontSize: 16,
    fontFamily: "Helvetica Neue",
    fontWeight: "500",
    color: "hsl(0, 0%, 100%)",
  },
  existingPlaylistMeta: {
    fontSize: 13,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 60%)",
  },
  // Manage Mixes Modal Styles
  manageMixesModalContent: {
    backgroundColor: "hsl(0, 0%, 8%)",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "80%",
    width: "100%",
    maxWidth: 500,
    paddingBottom: 20,
  },
  manageMixesModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "hsl(0, 0%, 15%)",
  },
  manageMixesModalTitle: {
    fontSize: 20,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 100%)",
    fontWeight: "bold",
  },
  manageMixesModalClose: {
    padding: 4,
  },
  manageMixesLoadingContainer: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  manageMixesLoadingText: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 60%)",
  },
  manageMixesEmptyContainer: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  manageMixesEmptyText: {
    fontSize: 18,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 100%)",
  },
  manageMixesEmptySubtext: {
    fontSize: 14,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 60%)",
    textAlign: "center",
  },
  manageMixesScroll: {
    maxHeight: 400,
  },
  manageMixItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "hsl(0, 0%, 15%)",
  },
  manageMixItemInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 12,
  },
  manageMixItemImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
  },
  manageMixItemDetails: {
    flex: 1,
    gap: 4,
  },
  manageMixItemTitle: {
    fontSize: 16,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 100%)",
  },
  manageMixItemGenre: {
    fontSize: 13,
    fontFamily: "Helvetica Neue",
    color: "hsl(0, 0%, 60%)",
  },
  manageMixBadges: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 4,
  },
  manageMixPrimaryBadge: {
    backgroundColor: "hsl(75, 100%, 60%)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  manageMixPrimaryText: {
    fontSize: 11,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 0%)",
  },
  manageMixPinnedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "hsl(75, 100%, 60%, 0.15)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  manageMixPinnedText: {
    fontSize: 11,
    fontFamily: "TS Block Bold",
    color: "hsl(75, 100%, 60%)",
  },
  manageMixActionButtonPinned: {
    backgroundColor: "hsl(75, 100%, 60%, 0.1)",
  },
  manageMixActionTextPinned: {
    color: "hsl(75, 100%, 60%)",
  },
  manageMixItemActions: {
    flexDirection: "row",
    gap: 8,
  },
  manageMixActionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "hsl(0, 0%, 12%)",
  },
  manageMixActionButtonDelete: {
    backgroundColor: "hsl(0, 0%, 12%)",
  },
  manageMixActionText: {
    fontSize: 13,
    fontFamily: "Helvetica Neue",
    color: "hsl(75, 100%, 60%)",
  },
  manageMixActionTextDelete: {
    color: "hsl(0, 100%, 50%)",
  },
  manageMixesModalFooter: {
    padding: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "hsl(0, 0%, 15%)",
  },
  manageMixesUploadButton: {
    borderRadius: 12,
    overflow: "hidden",
  },
  manageMixesUploadGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 20,
  },
  manageMixesUploadText: {
    fontSize: 16,
    fontFamily: "TS Block Bold",
    color: "hsl(0, 0%, 0%)",
  },
});

export default styles;
