/**
 * Discover feed, carousels, opportunity cards, location / sheet modals.
 */
import { FONT_BODY, FONT_HEADING, cardTile } from "./tokens";

export default {
  discoverList: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
  },
  communitySubtitleSection: {
    marginBottom: 12,
  },
  communitySubtitle: {
    fontSize: 18,
    fontFamily: FONT_HEADING,
    color: "hsl(0, 0%, 100%)",
    letterSpacing: 0.5,
  },
  discoverCard: {
    padding: 16,
    marginBottom: 16,
    ...cardTile,
  },
  discoverTopRow: {
    flexDirection: "row",
    marginBottom: 12,
    alignItems: "flex-start",
  },
  discoverProfileContainer: {
    marginRight: 16,
    position: "relative",
  },
  discoverProfileImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  discoverNameSection: {
    flex: 1,
    marginRight: 12,
  },
  discoverHeader: {
    marginBottom: 4,
  },
  discoverName: {
    fontSize: 16,
    fontFamily: FONT_HEADING,
    color: "hsl(0, 0%, 100%)",
    marginBottom: 2,
  },
  discoverOnlineIndicator: {
    position: "absolute",
    bottom: 2,
    right: 2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "hsl(120, 100%, 50%)",
    borderWidth: 3,
    borderColor: "hsl(0, 0%, 8%)",
  },
  discoverUsername: {
    fontSize: 14,
    fontFamily: FONT_BODY,
    color: "hsl(75, 100%, 60%)",
    marginBottom: 2,
  },
  discoverLocation: {
    fontSize: 14,
    fontFamily: FONT_BODY,
    color: "hsl(0, 0%, 70%)",
    marginBottom: 8,
  },
  discoverBio: {
    fontSize: 14,
    fontFamily: FONT_BODY,
    color: "hsl(0, 0%, 70%)",
    lineHeight: 18,
    marginBottom: 12,
  },
  // Status line under location in Discover cards.
  // Keep it readable on black and aligned with brand neutrals.
  discoverStatus: {
    fontSize: 13,
    fontFamily: FONT_BODY,
    color: "hsl(0, 0%, 78%)",
    lineHeight: 17,
    marginBottom: 12,
    fontStyle: "italic",
  },
  discoverGenres: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 12,
  },
  discoverGenreTag: {
    backgroundColor: "hsl(0, 0%, 15%)",
    borderWidth: 1,
    borderColor: "hsl(75, 100%, 60%)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 6,
    marginBottom: 4,
  },
  discoverGenreText: {
    fontSize: 11,
    fontFamily: FONT_BODY,
    color: "hsl(0, 0%, 100%)",
    fontWeight: "500",
    marginLeft: 4,
  },
  discoverRatingSection: {
    alignItems: "flex-end",
    minWidth: 60,
  },
  discoverRatingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  discoverRating: {
    fontSize: 14,
    fontFamily: FONT_BODY,
    fontWeight: "600",
    color: "hsl(45, 100%, 50%)",
    marginLeft: 4,
  },
  discoverLastActive: {
    fontSize: 12,
    fontFamily: FONT_BODY,
    color: "hsl(0, 0%, 70%)",
  },
  discoverActions: {
    flexDirection: "row",
    gap: 12,
  },
  discoverViewProfileButton: {
    backgroundColor: "hsl(0, 0%, 15%)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    gap: 6,
    flex: 1,
  },
  discoverViewProfileText: {
    fontSize: 14,
    fontFamily: FONT_BODY,
    fontWeight: "600",
    color: "hsl(0, 0%, 100%)",
  },
  discoverConnectButton: {
    backgroundColor: "hsl(75, 100%, 60%)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    gap: 6,
    flex: 1,
  },
  discoverMessageButton: {
    backgroundColor: "hsl(75, 100%, 60%)",
  },
  discoverMessageText: {
    fontSize: 14,
    fontFamily: FONT_BODY,
    fontWeight: "600",
    color: "hsl(0, 0%, 0%)",
  },
  discoverConnectedButton: {
    backgroundColor: "hsl(0, 0%, 30%)",
    opacity: 0.8,
  },
  discoverPendingButton: {
    backgroundColor: "hsl(0, 0%, 12%)",
    borderWidth: 1,
    borderColor: "hsl(75, 100%, 60%)",
  },
  discoverConnectText: {
    fontSize: 14,
    fontFamily: FONT_BODY,
    fontWeight: "600",
    color: "hsl(0, 0%, 0%)",
  },
  discoverConnectedText: {
    color: "hsl(0, 0%, 100%)",
  },
  discoverPendingText: {
    color: "hsl(75, 100%, 60%)",
  },
  sectionHeaderLink: {
    fontSize: 13,
    fontFamily: FONT_BODY,
    fontWeight: "600",
    color: "hsl(75, 100%, 60%)",
    paddingVertical: 4,
    paddingLeft: 12,
  },
  recommendationsSection: {
    marginBottom: 24,
  },
  recommendationsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
    width: "100%",
  },
  recommendationsTitle: {
    flex: 1,
    fontSize: 18,
    fontFamily: FONT_HEADING,
    color: "hsl(0, 0%, 100%)",
    letterSpacing: 0.5,
    marginRight: 8,
  },
  recommendationsScroll: {
    marginHorizontal: -20,
  },
  recommendationsContent: {
    paddingHorizontal: 20,
    gap: 12,
  },
  discoverCarouselSkeletonCard: {
    width: 160,
    height: 200,
    borderRadius: 12,
    backgroundColor: "hsl(0, 0%, 12%)",
    borderWidth: 1,
    borderColor: "hsl(0, 0%, 18%)",
  },
  opportunityCarouselSkeletonCard: {
    width: 200,
    height: 240,
    borderRadius: 12,
    backgroundColor: "hsl(0, 0%, 12%)",
    borderWidth: 1,
    borderColor: "hsl(0, 0%, 18%)",
  },
  recommendationCard: {
    width: 160,
    height: 200,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "hsl(75, 100%, 60%, 0.1)",
  },
  recommendationImageContainer: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  recommendationImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "hsl(0, 0%, 12%)",
  },
  recommendationImagePlaceholderRoot: {
    justifyContent: "center",
    alignItems: "center",
  },
  recommendationGradient: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "50%",
  },
  recommendationInfo: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 12,
    gap: 4,
  },
  recommendationTitle: {
    fontSize: 14,
    fontFamily: FONT_BODY,
    fontWeight: "600",
    color: "hsl(0, 0%, 100%)",
  },
  recommendationArtist: {
    fontSize: 12,
    fontFamily: FONT_BODY,
    color: "hsl(75, 100%, 60%)",
  },
  recommendationGenre: {
    fontSize: 11,
    fontFamily: FONT_BODY,
    color: "hsl(0, 0%, 60%)",
    marginTop: 2,
  },
  nearbyEmptyCard: {
    minHeight: 108,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "hsl(0, 0%, 18%)",
    backgroundColor: "hsl(0, 0%, 10%)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    gap: 6,
  },
  nearbyEmptyTitle: {
    fontSize: 14,
    fontFamily: FONT_HEADING,
    color: "hsl(0, 0%, 100%)",
    letterSpacing: 0.3,
  },
  nearbyEmptySubtitle: {
    fontSize: 12,
    fontFamily: FONT_BODY,
    color: "hsl(0, 0%, 62%)",
    textAlign: "center",
  },
  recommendationsDivider: {
    height: 1,
    backgroundColor: "hsl(0, 0%, 15%)",
    marginTop: 24,
  },
  opportunityCard: {
    width: 200,
    height: 240,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "hsl(75, 100%, 60%, 0.15)",
    backgroundColor: "hsl(0, 0%, 8%)",
  },
  opportunityImageContainer: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  opportunityImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "hsl(0, 0%, 12%)",
  },
  opportunityImagePlaceholderRoot: {
    justifyContent: "center",
    alignItems: "center",
  },
  opportunityGradient: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "60%",
  },
  opportunityInfo: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 14,
    gap: 6,
  },
  opportunityTitle: {
    fontSize: 15,
    fontFamily: FONT_HEADING,
    color: "hsl(0, 0%, 100%)",
    fontWeight: "600",
  },
  opportunityVenue: {
    fontSize: 13,
    fontFamily: FONT_BODY,
    color: "hsl(75, 100%, 60%)",
    fontWeight: "500",
  },
  opportunityMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  opportunityMetaText: {
    fontSize: 11,
    fontFamily: FONT_BODY,
    color: "hsl(0, 0%, 70%)",
  },
  opportunityCompensation: {
    fontSize: 12,
    fontFamily: FONT_BODY,
    color: "hsl(75, 100%, 60%)",
    fontWeight: "600",
    marginTop: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  locationModalBackdrop: {
    flex: 1,
    minHeight: 48,
  },
  locationModalKeyboardAvoid: {
    width: "100%",
  },
  modalContent: {
    backgroundColor: "hsl(0, 0%, 8%)",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "60%",
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "hsl(0, 0%, 15%)",
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: FONT_HEADING,
    color: "hsl(0, 0%, 100%)",
  },
  locationModalBody: {
    padding: 20,
    gap: 20,
  },
  locationModalDescription: {
    fontSize: 14,
    fontFamily: FONT_BODY,
    color: "hsl(0, 0%, 60%)",
    lineHeight: 20,
  },
  locationInputContainer: {
    gap: 12,
  },
  locationInput: {
    backgroundColor: "hsl(0, 0%, 12%)",
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    fontFamily: FONT_BODY,
    color: "hsl(0, 0%, 100%)",
    borderWidth: 1,
    borderColor: "hsl(0, 0%, 20%)",
  },
  useCurrentLocationButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "hsl(0, 0%, 12%)",
    borderWidth: 1,
    borderColor: "hsl(75, 100%, 60%, 0.3)",
  },
  useCurrentLocationText: {
    fontSize: 14,
    fontFamily: FONT_BODY,
    color: "hsl(75, 100%, 60%)",
    fontWeight: "600",
  },
  locationModalActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
  },
  locationModalCancelButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    backgroundColor: "hsl(0, 0%, 12%)",
    alignItems: "center",
  },
  locationModalCancelText: {
    fontSize: 16,
    fontFamily: FONT_BODY,
    color: "hsl(0, 0%, 100%)",
    fontWeight: "600",
  },
  locationModalSaveButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    backgroundColor: "hsl(75, 100%, 60%)",
    alignItems: "center",
  },
  locationModalSaveButtonDisabled: {
    opacity: 0.5,
  },
  locationModalSaveText: {
    fontSize: 16,
    fontFamily: FONT_HEADING,
    color: "hsl(0, 0%, 0%)",
  },
};
